# Makefile - Sustentacion
#
# autor: Carlos Alberto Llano R.
# fecha: Jun. 22/2013
# ultima modificacion: Jun. 22/2013
#

SRC = presentation.tex

presentation:
	pdflatex presentation.tex
	pdflatex presentation.tex
	evince presentation.pdf

clean:
	rm -f *.log
	rm -f *.out
	rm -f *.aux
	rm -f *.toc
	rm -f *.dvi
	rm -f *.blg
	rm -f *~
	rm -f *.lot
	rm -f *.lof
	rm -f *.loa
	rm -f *.ps
	rm -f *.idx
	rm -f *.ind
	rm -f *.ilg
	rm -f *.nav
	rm -f *.snm